### ISSUE TITLE
print_summary missed important error

### ISSUE THREAD

**Issue by ambarb** [bluesky/bluesky#1173]
To run reciprocal space scans, I have to calculated the angles in spec and then dump them in a textfile that I load into python.  Sometimes, I forget to "Cntrl S" on jupyterhub so the file in my directory that has the diffractometer positions and energy is empty when i copy to the beamline workstation directory.

This was the case when I ran `print _summary()`, but nothing stopped the text generation to the terminal.  It is too much to go through every line.  `check_limits()` works, it found the empty file in the file ending in '...neighbor.txt'.

This was applied to `plan_100K_dinner_20182504()`

```python
def Escan_fixed_q(file ='Escan_112_100K_L3.txt' ): 
    Qs = np.loadtxt(file)
    where = [delta.user_readback.value, theta.user_readback.value, gamma.user_readback.value, pgm.energy.setpoint.value ]
    for q in Qs:
        yield from mv(delta, q[3], theta, q[4], gamma, q[5], pgm.energy, q[6])
        yield from count([fccd, pgm.energy], md={'reason':'fixed Q {} {} {}'.format(q[0],q[1],q[2])})
    yield from mv(delta, where[0], theta, where[1], gamma, where[2], pgm.energy, where[3])
        
def plan_100K_dinner_20182504():
    #yield from mv(fccd.exposure, (0.1,0.1,10))
    #yield from ct_dark(50)
    #yield from Escan_fixed_q('Escan_112_100K_L3.txt')
    yield from Escan_fixed_q('Escan_112_100K_L3_exact.txt')
    yield from Escan_fixed_q('Escan_112_100K_L3_exact_neighbor.txt')
    
```

**Comment by awalter-bnl** [comment]
Hi Andi, Can I ask for some clarification. I suspect that the issue here is the loop, `for q in Qs` in `Escan_fixed_q`. Is it correct that the output only printed the move statements from the final `yield` and not from any of the `yields` inside the loop?

From my point of view this is a very specific case where `print_summary` won't catch an error related to a very specific custom plan. I do not see anyway to catch such a specific error in `print_summary` itself as it is agnostic about details of the plan and can only ensure that the 'messages' returned by the plan are actionable. In `Escan_fixed_q` an empty file results in an empty `Qs` dictionary and hence the part in the loop never generates the messages to be checked by `print_summary`. Does anyone else from DAMA have any ideas?

The best solution for me here is to add to `Escan_fixed_q` an `if Qs` loop of the type:
```
if Qs:
     for q in Qs:
         yield from mv(delta, q[3], theta, q[4], gamma, q[5], pgm.energy, q[6])
         yield from count([fccd, pgm.energy], md={'reason':'fixed Q {} {} {}'.format(q[0],q[1],q[2])})
         yield from mv(delta, where[0], theta, where[1], gamma, where[2], pgm.energy, where[3])
else:
   raise ValueError('the specified file is empty') 
```
Or alternatively, write a function that loads the file that checks if the file is empty, along the lines of.

```
def load_and_check_file(filepath):
    Qs = np.loadtxt(file)
    if not QS:
        raise (ValueError('the specified file is empty')
    return Qs
```

This would then replace the first line in the `Escan_fixed_q` plan and ensure that an error is generated any time the plan is run (including when `print_summary` is used).

Hopefully this helps.

**Comment by tacaswell** [comment]
I agree with @awalter-bnl , I don't see how we could reasonably catch that your plan did not do something you expected it to (we can only act on what it _did_ do).

Of the two suggestions, I think the second one is better (as it localizes the error to the code that is at fault so when you get the trace back you see the `if not len(Qs):` immediately above the line that raised and then immdiantly above that you see the `loadtxt`).

I'm going to close this as I think the underlying issue is that `print_summary` is too verbose / we need better previewers.

@ambarb can you please comment on https://github.com/bluesky/bluesky-enhancement-proposals/issues/13 ?

**Comment by ambarb** [comment]
I understand that you want me to write better code, but I should not have to write this code to do this work. There is currently not a pyhkl engine that will do these calculations for our diffractometer and this is the solution that I was able to implement. 

That said, in the past if I have something like :
```python
scans = [356]
t = db[scans[0]].table()
```
I get an exception about scans not be iterate-able unless I use `scans = [356,]`.  With this knowledge, I would have expected an exception when the text file is empty because `Qs` is not a list any longer (an empty text file).  Is this incorrect thinking on my part?  How is this flawed logic?  It seems that python should inherently catch this error that I created and it should not depend on the user to understand how print_summary works at the lower levels.

Even I did not have to do the experiment in this way,  if we (as in a facility) are going to start to use analysis code of some sort to then decide what to do next in an experiment, will people use output files to do this in prototyping before ophyd devices are built to handling these things?  If the answer is maybe, then perhaps this is something to think about in advance of having a problem that isn't as innocuous as the example with `Qs`.
