### ISSUE TITLE
make sure BEC never kills a plan due to raising an exception

### ISSUE THREAD

**Issue by tacaswell** [bluesky/bluesky#1184]

**Comment by CJ-Wright** [comment]
Should we advocate for putting non-breaking callbacks on a proxy?

**Comment by tacaswell** [comment]
@CJ-Wright that is also a solution, but going from 0 to running proxy is not trivial on the floor.

**Comment by danielballan** [comment]
Should we add an `ignore_exceptions` kwarg to `RunEngine.subscribe`? We have an instance-global switch `RunEngine.ignore_callback_exceptions` which is too broad (it would ignore `db.insert` failure too). Maybe the right place for that switch is on a per-subscription basis.

One reason _not_ to do this is that ignoring exceptions isn't always enough. In the case of pyolog, we have to also process the callbacks on a Thread because the pyolog sometimes fails by being slow.

**Comment by danielballan** [comment]
Closed by #1249
