### ISSUE TITLE
scan() accepts num=0.1 and does nothing but should give warning or error

### ISSUE THREAD

**Issue by jklynch** [bluesky/bluesky#1198]
The scan() plan accepts num=0.1 and behaves as if num=0. This seems like something a user would not expect.

## Expected Behavior
I think an error or warning should be displayed to the user.

## Current Behavior
scan(..., num=0.1) seems to do nothing.

**Comment by danielballan** [comment]
Good catch! I'm surprised this has not been reported before.

I propose that in all scans that accept some number of steps `num`, we do the following check:

```python
if not (float(num).is_integer() and num > 0):
    raise ValueError(f"The parameter `num` is expected to be a number of steps (not step size!) "
                     f"It must therefore be a whole number. The given value was {num}.")
```

I am suggesting `ValueError` not `TypeError` because I think that we ought accept `float` objects and `int` objects so long as the `float` objects (which are actually doubles in Python) represent integer values, as in:

```python
In [1]: 2.0.is_integer()
Out[1]: True
```
