### ISSUE TITLE
Qt Errors on 1.6.0rc

### ISSUE THREAD

**Issue by CJ-Wright** [bluesky/bluesky#1222]
I was testing out things with the new RC and qt segfaulted.

## Current Behavior
a bunch of 
`QObject::startTimer: Timers can only be used with threads started with QThread`
then some
`QObject::setParent: Cannot set parent, new parent is in a different thread`
and a segfault while trying to run a simple scan with best effort callback enabled

## Steps to Reproduce (for bugs)
```python
from bluesky import RunEngine
from ophyd.sim import hw, SynSignal
from xpdan.vend.callbacks.best_effort import BestEffortCallback
import bluesky.plans as bp
import matplotlib.pyplot as plt
plt.ion()
hw = hw()

m1 = hw.motor1
m1.kind = 'hinted'

def parab():
    x = m1.readback.value
    return -(x-6)**2 + 6

sig = SynSignal(func=parab, name='det')
sig.kind = 'hinted'
RE = RunEngine()
bec = BestEffortCallback()
RE.subscribe(bec)
RE(bp.scan([sig], m1, 0, 12, 13))
plt.show()
```
with v1.6.0rc as the bluesky version (note that this works for v1.5.3)

## Your Environment
working on it

**Comment by tacaswell** [comment]
Thank you for testing @CJ-Wright !

You need to update your vendored `BEC` and / or sub-class from https://github.com/bluesky/bluesky/blob/d26253e1a096018bf0e2d5885a655344e24a48bc/bluesky/callbacks/mpl_plotting.py#L19-L36

The issue is that 
 1. the asyncio event loop now runs on a background thread
 2. the callbacks are run synchronously in-line in the event loop
 3. you can only do (most) Qt things from the main thread

The above callback works around this by using signal/slots to move the actual execution back to the main thread (which while RE is running is is blocking on the Qt event loop).
