### ISSUE TITLE
is the "position" attribute a real thing?

### ISSUE THREAD

**Issue by untzag** [bluesky/bluesky#1393]
The docs mention that settable hardware objects should implement `position`, "a heuristic that describes the current position of a device as a single scalar, as opposed to the potentially multi-valued description provided by `read()`" [1]. As far as I can tell, this isn't a real thing? I don't see ophyd devices implementing `position`.

Any clarification would be appreciated :smile: 

[1] https://blueskyproject.io/bluesky/hardware.html#position

**Comment by prjemian** [comment]
* https://github.com/bluesky/ophyd/blob/5734e401c887d8ddbe564daa840c8b8a4a1f7d5a/ophyd/epics_motor.py#L183-L192
* https://github.com/bluesky/ophyd/blob/19237e3063889659637c880c3818c34e8c72e769/ophyd/positioner.py#L218-L226

**Comment by untzag** [comment]
Thanks for your response, @prjemian, I missed that!

> I don't see ophyd devices implementing position.

All I actually did was look at the motor objects at https://try.nsls2.bnl.gov/, those do not implement `position` from what I can see?

Do we wish to enforce the position attribute in `is_movable`? Is it used by the run engine?

**Comment by ksunden** [comment]
https://github.com/bluesky/bluesky/blob/4fab894bddbd4a563f28852ea3171b87140ae7b9/bluesky/preprocessors.py#L977

A quick search shows that it is only used once inside the library (used a few times in tests as well)

Even here, there is fallback behavior, so not 100% required

**Comment by untzag** [comment]
Yeah, my original observation was that my `yaqc_bluesky.Device` objects seem to work just perfect without `position`.

**Comment by prjemian** [comment]
Not sure the bluesky package needs to use the ophyd `.position` property but instrument plans might make heavy use of this shortcut to `motor.user_readback.get()`.  See for example this search for `.position` in the APS USAXS instrument repository:

https://github.com/APS-USAXS/ipython-usaxs/search?q=.position&unscoped_q=.position

It's a great tool for the command-line user and for user plans.

**Comment by untzag** [comment]
Ah, I see... :thinking:

**Comment by prjemian** [comment]
Positioner objects should work without the `.position` property but users familiar with Bluesky will miss this shortcut if not provided.

Point of interest, *I believe* it was inherited into ophyd from the PyEpics support for the EPICS motor record.  Still, there, as a shortcut.

**Comment by untzag** [comment]
I can totally see why `position` is generally useful---I'm just wondering if we want to enforce it for all bluesky interface objects or have it be just an optional extra that ophyd does sometimes. I believe that @tacaswell told me that `set` is very flexable and supports interfaces with very rich state, so I wonder if `position` is unreasonable to expect of generic bluesky interfaces.

I appreciate that this isn't a very practical question... Personally all of my interfaces work fine with `position` so I'm happy to keep it.

**Comment by prjemian** [comment]
`set()` is general for ophyd Signals.  `position` is specific to ophyd Positioner *Devices*.  If positioners subclass from [`ophyd.positioner.PositionerBase`](https://github.com/bluesky/ophyd/blob/19237e3063889659637c880c3818c34e8c72e769/ophyd/positioner.py#L15), they'll get the `.positioner` property.  Subclasses can override as they choose but it is provided.

Not used for ophyd `Signals`.  For those, there is a (similar) [`.value` property](https://github.com/bluesky/ophyd/blob/8efd645e394e15a484d5bfadf8c5c87a2d1ed240/ophyd/signal.py#L310-L327) which creates a warning now (means: use `.get()` instead of `.value`, at least for now).  The source code has some documentation on this.

**Comment by danielballan** [comment]
> I can totally see why position is generally useful---I'm just wondering if we want to enforce it for all bluesky interface objects or have it be just an optional extra that ophyd does sometimes. 

It is an optional extra that ophyd does sometimes, primarily used when people are poking ophyd devices interactively, _sans_ bluesky. We try very hard to avoid using `.position` or `.get()` or anything that communicates directly with hardware in bluesky or in bluesky plans, because it enables simulators like `summarize_plan(...)` ,`check_limits(...)`, and the long-dreamed-of-but-not-yet-implemented `estimate_time(...)` to consume the plan _without causing hardware interaction_. That only works if plans are careful to avoid touching hardware in a way that bluesky cannot intercept.

**Comment by prjemian** [comment]
As Dan implied, the bluesky RunEngine is not the only software that might review the actions of a plan.  Make sure your plans have *instructions* for actions, without actually *acting* on them.

**Comment by untzag** [comment]
OK, I _think_ what I've heard is that y'all like the idea of `position` and think that it should stay a popular convention, but `position` should be considered an optional attribute for the movable interface.
