### ISSUE TITLE
Need a new type of `Movable` that lets you see where it actually is

### ISSUE THREAD

**Issue by coretl** [bluesky/bluesky#1535]
Name:
- `Locatable`
- ...
Methods:
- `get_setpoint() -> SyncOrAsync[Any]` and `get_position() -> SyncOrAsync[Any]`
- `get_setpoint() -> SyncOrAsync[Any]` and `get_readback() -> SyncOrAsync[Any]`
- ...

**Comment by coretl** [comment]
This is the best @tacaswell @danielballan @coretl and @callumforrester could come up with...

```python
@dataclass
class Location(Generic[T]):
    setpoint: T
    readback: T

class Locatable:
    def get_location(self) -> SyncOrAsync[Location]:
       ...
```

**Comment by untzag** [comment]
Why is this a dataclass rather than two separate messages? Is it so that we can guarantee self-consistency in an async context? Similar to why subscribe needs to actually return reads?

**Comment by tacaswell** [comment]
The issue is that in some context "where it is" is "obviously" what the hardware actually says, on other cases where it is is "obviously" the setpoint (and yes the hardware might have moved away but it is in the dead band and than is OK).  Having `get_location` or `get_position` return one or the other of those is not great (because people will assume it is the other one no matter which way we pick).   We could have `get_readback` and `get_setpoint` that return scalars on the device, but those are not the most memorable.  

Hence, we give the nice name to something that gives both and then do structured access inside.

This would likely not get its own message, but be used by plans (most critically by the relative plans, see #1431 ).

**Comment by tacaswell** [comment]
I think 3 and provide a reference version of `Location` else where in the concrete implementation of ophyd.

**Comment by untzag** [comment]
For what it's worth I vote 2. `Location` has deep similarity to `Reading`.

**Comment by coretl** [comment]
I'm on the fence between 2 and 3. Any more votes?

**Comment by tacaswell** [comment]
However, I think that if we had had data classes when we started, `Reading` would have been a dataclass not a dict and dot access is very nice here (and every version of "lets add dot access to dictionaries" has been a choice I eventually regretted).

**Comment by coretl** [comment]
@tacaswell I can see this being used in `bps.rd` and `bps.movr`, but is a user ever likely to use this? If so then I think dataclass is preferable, but if we only ever use it in those two plan stubs I think I prefer consistency with `Reading`, so using a dict.

**Comment by prjemian** [comment]
For certain I will need more Python education to understand the structures
discussed here.

**Comment by tacaswell** [comment]
I hope user-users will not use this, but I suspect we will use it while debugging.

**Comment by coretl** [comment]
I'm erring on the side of 2 then. @tacaswell how strong is your preference for 3?

**Comment by tacaswell** [comment]
The argument to match `read` is compelling enough to go with 2.
