### ISSUE TITLE
bug: Incompatible with zict 3.0.0

### ISSUE THREAD

**Issue by rosesyrett** [bluesky/bluesky#1577]
While looking at merging a PR it was found that CI jobs were failing as they were using the latest (breaking) version of zict.

## Expected Behavior
Job should not fail

## Current Behavior
CI Job fails.

## Possible Solution
Someone should investigate why it's failing, exactly; we know it's a zict problem but not sure how/why.

## Steps to Reproduce (for bugs)
see https://github.com/bluesky/bluesky/pull/1575

## Context
I have a small PR (one line change) open to change something about bluesky FailedStatus tracebacks. The CI jobs for this are all failing. 

Upon closer inspection the culprit is the zict library 3.0.0 upgrade.

## Your Environment
See  https://github.com/bluesky/bluesky/pull/1575

A PR to temporarily pin zict for now has been opened.

**Comment by dmgav** [comment]
The issue is related to the following PR https://github.com/dask/zict/pull/90, particularly to https://github.com/dask/zict/blob/910c63e455fd59c5ab5f88589d5a93378782cf0e/zict/file.py#L83-L85

```
        key = quote(key, safe="") + f"#{self._inc}"
        self._inc += 1
        return key
```
Now the file name with stored dictionary value is changed each time it is modified, e.g.
```
p = PersistenDict("/tmp/test")
p['a'] = 10   # Saved to '/tmp/test/a#0'
p['b'] = 20  # Saved to '/tmp/test/a#1' and '/tmp/test/a#0' is deleted
# etc.
```
This scheme may be safer when using the same instance of the dictionary from multiple threads, but it does not function properly if two independent instances of the dictionary are opened simultaneously and attempt to modify and read data, but have no way to synchronize `self._inc` and fail trying to read wrong file, such as in `test_persistent_dict`: https://github.com/bluesky/bluesky/blob/19a528bd034af70692cbba262fc469b13da5b77b/bluesky/tests/test_persistent_dict.py#L19-L26 which fails executing `actual.reload()`. 

The fix will likely require rewrite of `PersistentDict`.

**Comment by mrakitin** [comment]
@dmgav, thanks for providing the thorough analysis of the issue. Do you think we can try to fix the issue? This is blocking the removal of the `zict <3.0.0` pin which prevents us from using the latest dask needed at NSLS-II at some beamlines.
