### ISSUE TITLE
Add warning when plan not iterated

### ISSUE THREAD

**Issue by coretl** [bluesky/bluesky#1632]
## Expected Behavior

At the moment, it is very easy to forget to `yield from` in the middle of the plan, and there don't appear to be any warnings that appear when a plan stub is created but not iterated. To contrast, `asyncio` will warn on garbage collect of any coroutine that is not awaited. It would be nice to do the same.

## Current Behavior

```python
from bluesky import RunEngine
import bluesky.plan_stubs as bps

RE = RunEngine()

def my_plan():
    yield from bps.null()
    bps.sleep(10)

RE(my_plan())
```

Nothing is printed, vs the asyncio:
```python
import asyncio

async def my_func():
    asyncio.sleep(1)

asyncio.run(my_func())
```
which prints
```
RuntimeWarning: coroutine 'sleep' was never awaited
  asyncio.sleep(1)
```

## Possible Solution

We could decorate the function with something that tracks iteration and raises on `__del__`:

```python
# utils.py
import traceback

class EnsureIterated:
    def __init__(self, f, *args, **kwargs):
        self._iter = f(*args, **kwargs)
        self._stack = traceback.format_stack()
        self._stack += [f"RuntimeWarning: plan `{f.__name__}` was never iterated"]

    def __iter__(self):
        self._stack = None
        yield from self._iter

    def __del__(self):
        if self._stack:
            print(*self._stack)

def ensure_plan_iterated(f):
    # TODO: wrap with functools.wrap and sort out type hints
    def wrapper(*args, **kwargs):
        return EnsureIterated(f, *args, **kwargs)
    
    return wrapper
    

# plan_stubs.py
from bluesky import Msg

@ensure_plan_iterated
def sleep(time):
    return (yield Msg('sleep', None, time))


# my_plan.py
from bluesky import RunEngine

RE = RunEngine()

def my_plan():
    yield from sleep(0.1)
    sleep(10)

RE(my_plan())
```
will output
```
  File "/usr/lib/python3.10/threading.py", line 973, in _bootstrap
    self._bootstrap_inner()
   File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
   File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
   File "/usr/lib/python3.10/asyncio/base_events.py", line 600, in run_forever
    self._run_once()
   File "/usr/lib/python3.10/asyncio/base_events.py", line 1896, in _run_once
    handle._run()
   File "/usr/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
   File "/dls/science/users/tmc43/repos/bluesky/bluesky/run_engine.py", line 1532, in _run
    msg = self._plan_stack[-1].send(resp)
   File "/repos/bluesky/my_plan.py", line 41, in my_plan
    sleep(10)
   File "/repos/bluesky/my_plan.py", line 21, in wrapper
    return EnsureIterated(f, *args, **kwargs)
   File "/repos/bluesky/my_plan.py", line 7, in __init__
    self._stack = traceback.format_stack()
 RuntimeWarning: plan `sleep` was never iterated
```
This is a bit wordy, but demonstrates the principle...

@callumforrester @rosesyrett we talked about this issue a few days ago, maybe something like this would help?

**Comment by callumforrester** [comment]
In general I would be quite interested in other people's opinions on plans that are not realisable (i.e. would not come back if you just typed `list(my_plan())`. In particular regarding the original design story (@tacaswell @danielballan ).

The main pro is the ability to simulate and validate a plan ahead of time, the main con is the reduced flexibility from not being able to put whatever you want in the middle of a plan and needing a run engine message for everything. I can see the latter being the design intent though, since it is possible to define your own run engine messages.

**Comment by rosesyrett** [comment]
I like this idea, although I'd want to make the error message a bit more readable. In general error messages from the run engine are verbose, and I'm not sure I like the fact that I can see the innards of the run engine in them when the error has nothing to do with the run engine and everything to do with how my code is faulty. 

I think the asyncio error messages suffer the same problem; often when I see 'task was never awaited' or something similar I'm left scratching my head wondering where python was trying to garbage collect tasks and therefore which task it's complaining about. So I spend hours trying to find where exactly this is happening... instead of replicating asyncio's error messages I think we ought to outdo them a bit, and somehow have an error message that gives a traceback including your code that didn't have a `yield from`. Even putting something like, 'did you mean to use yield from?'

**Comment by coretl** [comment]
If we assume there is only one level of error, then we could look at the caller of our wrapper, discard the other lines, then fairly easily extract:
```
   File "/repos/bluesky/my_plan.py", line 41, in my_plan
    sleep(10)
 RuntimeWarning: plan `sleep` was never iterated, did you mean to use `yield from`?
```

You wouldn't get the caller (if it exists) of `my_plan`, but that is probably enough information to fix the issue...

**Comment by coretl** [comment]
BTW this `__del__` trick also works if you listify your plan, so you could `list(my_plan(())` to check if it had any missing `yield from`s and see the same warning...

**Comment by coretl** [comment]
@tacaswell @danielballan @prjemian @mrakitin thoughts?

**Comment by coretl** [comment]
> In general I would be quite interested in other people's opinions on plans that are not realisable (i.e. would not come back if you just typed `list(my_plan()`). In particular regarding the original design story (@tacaswell @danielballan ).
> 
> The main pro is the ability to simulate and validate a plan ahead of time, the main con is the reduced flexibility from not being able to put whatever you want in the middle of a plan and needing a run engine message for everything. I can see the latter being the design intent though, since it is possible to define your own run engine messages.

I'm also interested in this, but I'd prefer to discuss Attribute setting vs Message yielding in https://github.com/bluesky/ophyd-async/issues/40, while talking about mistakes (missing `yield from` statements) while instantiating plan stubs here

**Comment by tacaswell** [comment]
@callumforrester Being able to list-ify plans is a good thing, and more generally "naively" interating through plans as generators (rather than as generator-co-routines) as in https://github.com/bluesky/bluesky/blob/master/bluesky/simulators.py. In practice we have dealt with this in the plan by detecting when a `None` comes back.  For example https://github.com/bluesky/bluesky/blob/a8d4c77bd2d06a49fe2088c95d020abd427fd0a6/bluesky/plan_stubs.py#L409-L411

We have had some thoughts about adding a `Msg("who_are_you")` to query the execution engine about itself, but got caught on "should it return the RE instance or the name of the class or ....".  We did not have a clear use case that could not be handled by "well, if `None` came back we are being blindly iterated" so chose to do nothing rather than make a bad choice.

We have also had a couple of rounds of discussion of a default decorator to use on plans (some driven by this, some to make plans "self running" with a captive RE), but never converged (@ZLLentz and @klauer were involved in at least one round of those discussions iirc).  I think these decorators are OK, but am very (very) wary of making them mandatory.  The ability to pass a list of messages or a naive generator to the RE is very useful (generator co-routines are not generators you can send stuff to, generators are generator co-routines that ignore everything you send them ;) ).

**Comment by coretl** [comment]
>  I think these decorators are OK, but am very (very) wary of making them mandatory

@tacaswell would you be happy with something like a `ensure_plan_iterated` decorator added to all `plan_stubs` as long as it is transparent to the RE (i.e. not mandatory) and listifying plans still works?

**Comment by prjemian** [comment]
At some point, we discussed an optional @bluesky_plan_decorator for plans
which would mark a generator as intended for bluesky. You describe an
action this decorator could take in the case of plan stubs. Would there be
any difference between @bluesky_plan_decorator and
@bluesky_plan_stub_decorator?

**Comment by tacaswell** [comment]
The plan vs plan_stub distinction is for the humans (will it emit a `open_run` message?) so I would not expect there to be any difference in the decorators.

------

I would not say "happy", but I can not see any valid reason to argue against it so "accepting".

My concern is mostly vibes (getting farther from "standard" Python, slippery slope to making the class expected, more brains / state living in (sub)-classes, lingering fallout from when we did have class-based plans (they collapsed under their own weight)).

There are some subtle technical changes as `gen = my_plan(); assert iter(gen) is gen` works with un-decorated plans but is no longer true with the wrapped plan.  However getting multiple instances of `iter(gen)` still works as expected so I do not think this matters.

**Comment by coretl** [comment]
> I would not say "happy", but I can not see any valid reason to argue against it so "accepting".

I guess this is a trade-off, add some magic to warn users when they're doing something they might not have expected to do, or leave potential bugs to be discovered when the line of code is run (or later, as the consequences of not yielding a particular message to the RunEngine might not be noticed until the data was looked at).

Can you think of any less invasive magic that might give a similar effect?

I'm curious, do missing `yield from` statements often bite writers of plans, or is it just that we are relatively inexperienced with writing them at the moment? I've written `bps.mv(...)` a few times rather than `yield from bps.mv(...)` and not spotted it until a mysterious error surfaces much later...

**Comment by callumforrester** [comment]
@coretl would the proposed change actually help if you forget `yield from` in the case you gave? `bps.mv(...)` without a `yield from` is effectively a noop since it just produces a bunch of messages. So the following would go undetected

```python
def my_plan():
    yield from bps.mv(a, 1, b, 2)
    bps.mv(c, 3)

gen = my_plan()
iter(gen)  # This would still work!
```

Side note about regarding your question about how common this is: Writing `bps.mv(c, 3)` without a `yield from` felt _very_ weird, I wrote that example "correctly" twice, so there's one data point.

**Comment by coretl** [comment]
If `my_plan` contains a forgotten `yield from` then `RE(my_plan())` will moan, but `my_plan()` will not. If you want to detect rthis second case then you also need to decorate `def my_plan` with `@ensure_plan_iterated`.

I'm glad a left a working code snippet at the top of the file so I could actually test this...

**Comment by tacaswell** [comment]
Yes, so long as it is both optional and transparent.


-----

Re-reading this, I stand by my concern being "vibes" based and hence should not count for much.

**Comment by coretl** [comment]
> Yes, so long as it is both optional and transparent.

So if we make it optional (i.e. the RunEngine doesn't require you to decorate your plans to run them), but we decorate all the plan stubs in the bluesky repo with it then that would be ok?

I think the implementation at the top of the issue still stands, so is there anything else that needs to be added to it to aid transparency?

**Comment by vshekar** [comment]
I have a basic PR here for this issue: https://github.com/bluesky/bluesky/pull/1709
If someone has the bandwidth to review that would be great. I can also add tests to this PR (or a separate one) and apply the decorator to built in plans if that is the intention
