### ISSUE TITLE
BUG: search of documentation fails

### ISSUE THREAD

**Issue by prjemian** [bluesky/bluesky#1666]
Can't search the documentation for **anything**.  The web page shows an animated _Searching..._ but returns no results.  Here's an example searching for the word `status`:

![image](https://github.com/bluesky/bluesky/assets/2279984/08a6c3a8-da6d-4226-8b2d-59127eebce31)

**Comment by callumforrester** [comment]
This seems to work both locally and online with repositories that have adopted the new sphinx theme, such as ophyd: https://blueskyproject.io/ophyd/search.html?q=status

Suggest we make this ticket about adopting it into bluesky, but not changing the layout of the docs since that's a very large job involving lots of reviewers, per @danielballan.

**Comment by prjemian** [comment]
I confirm this solves the problem reported.
![image](https://github.com/bluesky/bluesky/assets/2279984/5974c4c9-13a8-4e4a-a9e3-7442ce6e5e52)

Thanks!
