### ISSUE TITLE
Lock beamline control so that only one Python process can caput.

### ISSUE THREAD

**Issue by danielballan** [bluesky/bluesky#17]

**Comment by tacaswell** [comment]
This needs to be a token that the run engine grabs when it starts and returns when it returns to idle.

**Comment by danielballan** [comment]
@stuwilks: "Do not lock it in /tmp. Do it with a PV."

**Comment by danielballan** [comment]
This could be accomplished using a collection of suspenders -- one per RunEngine instance --that are controlled by some hub that only allows one suspender to be un-tripped at time.

Incidentally, I believe we've already established that there is no way to keep some rogue RunEngine or some rogue caput from ignoring this constraint because ultimately EPICS does not care. This system would assume that all RunEngines are friendly RunEngines that install the necessary suspender.

Or, as others have said, there could be only one Special Process that is allowed to talk to the EPICS network.

I'm not aware that this is a priority for anyone; I'm just dropping the suggestion for Future Someone.

**Comment by danielballan** [comment]
In theory, one could secure Channel Access connections the same way we secure HTTP connections. HTTP doesn't have a concept of security either...

https://h11.readthedocs.io/en/latest/basic-usage.html

**Comment by awalter-bnl** [comment]
So this is another good idea, we have 2 endstations with seperate control computers so being bale to lock one out but not the other would be very useful. However, we would want to be able to define which motors are locked and which aren't in the setup files. 

In this way it combines nicely with the issue we have discussed regarding being able to define which 'plans' or RE processes are stopped by the suspenders and which are not.

**Comment by stuwilkins** [comment]
I wonder if this is a use for channel access security. It is fairly easy to setup (just a bit laborious as you need to put it on all IOCs) but it allows you to control which user or host can read or write PVs. We have implemented this to control EPUs etc so that one branch cannot inadvertently operate the others gap. Same for endstation controls. If you like @awalter-bnl I could show you how to set it up (with John). @danielballan what do you think, this might be a more appropriate layer?

**Comment by cowanml** [comment]
channel access security enables you to lock down read/write access to
pv's on a per host and/or user basis, but it can't distinguish between
multiple processes running under the same account on the same machine.

It's not *real* security, simple spoofing techniques easily work around it;
it's really just a layer of protection against inadvertent access.

That might acheive what you need?
but it won't lock it down to a single python process.
-matt

**Comment by awalter-bnl** [comment]
So we have different user accounts for the 2 endstations so this would probably resolve that issue.
we could just set the ARPES endstation motors to only be writeable from the ARPES endstation account. However when we swap from 1 branch to another it would be great to temporarily lockout PV access to the beamline PV's for the opposite branch account. We have a python plan that does the transfer, is it possible to have that change the read/write permissions?

**Comment by stuwilkins** [comment]
Yes @cowanml I was not suggesting this as security - apart from the fact that it is called _access security_.

http://www.aps.anl.gov/epics/base/R3-14/12-docs/AppDevGuide/node9.html

If you look at what Andrew wants to do (as I understand it @awalter-bnl) it is making sure that when one branch is operating it can pass over the _**con**_ to the other branch so users setting up on the other endstation can't advertently  change the optics etc. 

If this is the case then this could be done by just using the IP addresses of the two control computers. There would then be a PV which would allow the _con_  to be passed between the two endstations. You could even only make the restriction to the xf??id? account so that a beamline scientist could always log into the computers (or do su - _uname_) to be able to write to PVs. 

So, not security but just protecting from inadvertent control. I implemented this at CSX-{1,2} for exactly this reason and it works well.

**Comment by stuwilkins** [comment]
@awalter-bnl if you have two distinct endstation computers you don't need (but could have) different accounts. I can stop by tomorrow and show you what I am describing here if you like.

**Comment by awalter-bnl** [comment]
@stuwilkins We have 2 accounts and 2 workstations so it sounds like your solution at CSX is exactly what we need. I am at the CFN retreat tomorrow but Friday or next week is fine to meet to discuss this implementation.

**Comment by cowanml** [comment]
On Wed, 25 Oct 2017, Stuart Wilkins wrote:
> Yes @cowanml I was not suggesting this as security - apart from the fact that it is
> called access security.

didn't mean to imply you were, just felt compelled to add that
disclaimer since, as you point out, it's called "access security" and
we're discussing "locking" stuff...


...
> So, not security but just protecting from inadvertent control. I implemented this at
> CSX-{1,2} for exactly this reason and it works well.

yup, that's exactly what it's for and as long as there are distinct
computers (or accounts) involved it should solve the problem perfectly.

but you already knew that, so... in summary, "+1"
-matt

**Comment by danielballan** [comment]
We can't solve this properly at the bluesky layer, because someone could always use another client (e.g. `caput`, CSStudio) to run around it. We could add locking anyway to the RunEngine, but this opens up a can of worms (managing what happens to a lock when a process crashes, etc.) without really solving the problem thoroughly.

Locking needs to solved per-Device and at a different layer. This is something bluesky _project_ might someday address, but not in the bluesky library, so we are closing this issue.

**Comment by prjemian** [comment]
Commenting further, [EPICS Channel Access Security](https://epics.anl.gov/EpicsDocumentation/EpicsGeneral/WorkInProgress/casecsp.html) is used to provide some granularity to which EPICS clients (such as bluesky) can access (read and/or write) PVs.  Details of that security layer relevant to this issue are presented in section [*3.3 Restrict Channel Access Requests to "Authorized" Clients*](https://epics.anl.gov/EpicsDocumentation/EpicsGeneral/WorkInProgress/casecsp.html#HDR3.3%20%20%203%2010).

IIRC, the available security restrictions are limited to user ID and IP address but not to specific client processes at that IP address.  

I agree this issue should be closed.  The original concern would be advised to better identify the problem to be solved.
