### ISSUE TITLE
Connecting the RunEngine to Qt GUI via psygnal

### ISSUE THREAD

**Issue by jacopoabramo** [bluesky/bluesky#1847]
I'm trying to build a GUI application with Qt and the RunEngine inside it. I talked about this in the past with other people and the major problem was that using Qt signals would require inheriting from QObject which was undesirable.

I'm currently using [psygnal](https://github.com/pyapp-kit/psygnal) as a replacement for the Qt signals. It's a pure python implementation of the observer pattern and it can be used in connection with Qt application.

I'm attaching a minimal working example below:

[bluesky_playground.py.txt](https://github.com/user-attachments/files/17901466/bluesky_playground.py.txt) (remember to change file extension)
[requirements.txt](https://github.com/user-attachments/files/17901481/requirements.txt)

In the example a detector simply counts endlessly and updates a QLabel with it's data content.

I'm sure that there may be problems with this implementation so feel free to provide feedback. One thing I had to do was monkey patching the [install_remote_qt_kicker](https://github.com/bluesky/bluesky/blob/92d2633127e33e51aa1d1b109c80503e74bbe0e0/src/bluesky/utils/__init__.py#L997) function by doing the following:

```py
    _create_qApp()
    # qApp = matplotlib.backends.backend_qt.qApp
    from qtpy.QtWidgets import QApplication
    qApp = QApplication.instance()
```

I tried to write a kicker function without doing so but it wasn't working. This was the only way that I managed to do it.

EDIT: fixed typos

**Comment by jacopoabramo** [comment]
In the end I managed to resolve by reimplementing DuringTask

```python
class ProcessEventsDuringTask:
    """Implementation of DuringTask that emits events to the Qt event loop."""

    def __init__(self):
        super().__init__()
        self.app = QApplication.instance()

    def block(self, blocking_event: threading.Event):
        """Keep processing events until the blocking event is out of the "waiting" state.
        
        In the default implementation, blocking_event.wait() prevents 
        the Qt loop to correctly process events events. With this implementation we
        keep the Qt event loop alive while the task is running.
        """
        while True:
            done = blocking_event.wait(timeout=0.03)
            self.app.processEvents()
            if done:
                break
```

A truly Christmas miracle. Happy holidays everyone. Closing.

**Comment by tacaswell** [comment]
@jacopoabramo Would you be willing to PR that into the main code base?  I think the distinction is between a context where the main loop is anything _but_ the Qt event loop in which case we need to start and run one vs the case where the Qt event loop is _the_ main loop and we just need to turn the crank on processing events.

However, if you are running this in-process in something that is running a Qt event loop it is probably better to run `RE.__call__` on a QThread and use the trivial blocking event.

**Comment by tacaswell** [comment]
A version of the code you pasted as an alternative `DurringTask`.

-----

For context is a writup of how integrating multiple event loops works: 
https://matplotlib.org/stable/users/explain/figure/interactive_guide.html#event-loops .  This stuff is 

In your example you have `qApp.exec()` at the bottom so main loop that is running the show in the Qt main loop and everything you do in the program is triggered via callbacks (slots) in response to events landing on the Qt event queue (signals).  In general tasks run on the main loop of any event driven system should be "fast" so that the loop gets free again to handle the next thing.  If you have to run something "slow" you either need to push them to a background thread and keep tabs on it via callbacks or manually "spin" the event loop to flush any accumulated work.


In your example code, the function:

```python
    def start_plan(self) -> None:
        try:
            self.engine(self.live_plan())
        except RunEngineInterrupted:
            pass
    

```

will not return until the plan in done so the Qt event loop does not get control back until the plan finishes (and it is setup to be an infinite count so it will never return!).  Spinning the event loop "by hand" using either `qt_kicker` or via the during task works in that the application runs, but is less than ideal because you are effectively re-implementing the core Qt event loop in a less than ideal way.

**Comment by jacopoabramo** [comment]
@tacaswell sorry for the late reply. I see what you mean. Just for clarity, with this implementation the user sees taken away the control over pausing/stopping the plan execution via SIGINT and it is supposed to handle this via the UI, am I correct?

If that's okay with that I'll prepare a PR in the next days.
