### ISSUE TITLE
Unify the two approaches to logging callbacks in bluesky

### ISSUE THREAD

**Issue by ericdill** [bluesky/bluesky#293]
Two options here:
1. `jinja2` option should be a superset of the class-based callback
2. class-based callback should go away and `jinja2` option should be the only way to do logging.

This came up in discussion with @danielballan at CHX

**Comment by danielballan** [comment]
The main value of the `OlogCallback` is its access to the IPython command history. As discussed offline (awhile ago) this is problematic because the last IPython command does not always map 1:1 with the RunStart that triggered the log entry, and it rarely contains complete information (e.g., the state of `gs.DETS` or the starting positions of the motors).

Yugang has managed to write custom jinja templates and, working with me, dispatch to a custom template determined by the `plan_name`. This is now solving the problem that `OlogCallback` was solving in a "safer" way, IMO. So, given that, I think we can go with (2). Are you on board with that @ericdill?

**Comment by stuartcampbell** [comment]
@danielballan is this still relevant ?

**Comment by danielballan** [comment]
There are still two ways of doing this in bluesky that could be unified., `OlogCallback` and `logbook_cb_factory`, both in `bluesky.callbacks.olog`. But maybe we'll eventually land pyolog2 and write something around that instead that will supercede both of the current approaches.

**Comment by danielballan** [comment]
Decided as a group to close and focus efforts instead of finished pyolog2 and then writing a callback for _that_ where it should be easier to be general. Really this should be done in suitcase-olog.
